# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: pretty-format-json
        args: ['--autofix']
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: bashate
        description: This hook runs bashate for linting shell scripts
        entry: bashate
        language: python
        types: [shell]
-   repo: local
    hooks:
      - id: run-ut
        name: Run Pytest Tests with Coverage
        entry: poetry run pytest --cov=ures --cov-report=term-missing
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
