name: Publish Release Blog

on:
  release:
    types: [published]

jobs:
  blog-creating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/create-blog-in-hugo@trunk
        with:
          release-subject: ${{ github.event.release.name }} # Subject of the release
          release-body: ${{ github.event.release.body }} # Body of the release
          release-url: ${{ github.event.release.html_url }} # URL of the release
          python-version: "3.12" # Python version to use
          project-name: "URes"
          onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }} # 1Password service account token
