name: Release Blog

on:
  release:
    types: [published, edited]

jobs:
  post-release:
    runs-on: ubuntu-latest
    uses: stone-home/Action-Stone-Dev-Convention/.github/workflows/create_release_blog.yaml@trunk
    with:
      release-subject: ${{ github.event.release.name }}
      release-body: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      python-version: "3.11"
    secrets:
      onepass_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
