name: Publish Release to GitHub Page

on:
  release:
    types: [published]

jobs:
  gh-publish:
    name: Publish Document to GitHub Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/deploy-mkdocs-site@trunk
        with:
          python-version: "3.12"
          poetry-version: "2.3.2"
          onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }}
