name: Publish Current Version to PyPi
on:
  release:
    types: [published]
jobs:
  release:
    uses: stone-home/Action-Stone-DevOps/.github/workflows/w-v2-release.yaml@trunk
    with:
      version-id: ${{ github.event.release.name }}
      python-project: true
      python-version: "3.12"
      poetry-version: "2.3.2"
      pypi-enable: true
      pypi-token-path: "op://DevOps/PyPi Token/credential"
    secrets:
      onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }}
