name: Release
on: workflow_dispatch
#  push:
#    branches:
#      - trunk
permissions:
  contents: read # for checkout
jobs:
  release:
    uses: stone-home/Action-Stone-Dev-Convention/.github/workflows/release.yaml@trunk
    secrets:
      onepass_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
