name: Create a new release
on: workflow_dispatch
jobs:
  release:
    uses: stone-home/Action-Stone-DevOps/.github/workflows/w-v2-release.yaml@trunk
    with:
      python-project: false # Using basic release workflow to create a new release in GitHub
    secrets:
      onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }}
