name: Trufflehog
on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  secretCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/secret-check@trunk
