name: Trufflehog

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  secretCheck:
    uses: stone-home/Action-Stone-Dev-Convention/.github/workflows/secret-check.yaml@trunk
#    runs-on: ubuntu-24.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Secret Scanning
#        uses: trufflesecurity/trufflehog@main
#        with:
#          extra_args: --results=verified,unknown
