name: Testing

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  ut:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        poetry-version: ["1.8.5"]
    uses: stone-home/Action-Stone-DevOps/.github/workflows/pytest.yaml@trunk
    with:
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ matrix.poetry-version }}
