name: Testing

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  ut:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        poetry-version: ["2.1.3", "2.3.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: unit test
        uses: stone-home/Action-Stone-DevOps/.github/actions/python-poetry-test@trunk
        with:
          poetry-version: ${{ matrix.poetry-version }}
          python-version: ${{ matrix.python-version }}
